# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-TLVqH18MT0Nc86J4HPd7AUAQ-8mw4Z
"""

import numpy as np
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[9,8,7],[6,5,4],[3,2,1]])
matrix_sum=matrix1+matrix2
matrix_diff=matrix1-matrix2
matrix_product=matrix1*matrix2
matrix_divide=matrix1/matrix2
matrix_multiply=np.dot(matrix1,matrix2)
matrix1_transpose=np.transpose(matrix1)
diagonal_sum=np.trace(matrix1)
print("matrix1:\n",matrix1)
matrix2_transpose=np.transpose(matrix2)
diogonal_sum=np.trace(matrix1)
print("matrix1:\n",matrix2)
print("matrix2:\n",matrix2)
print("matrix_sum:\n",matrix_sum)
print("matrix_diff:\n",matrix_diff)
print("matrix_Element-wise product:\n",matrix_product)
print("matrix_Element-wise division:\n",matrix_divide)
print("matrix_multiply:\n",matrix_multiply)
print("Transpose of matrix 1:\n",matrix1_transpose)
print("sum of diagonal elements of matrix 1:\n",diagonal_sum)

